services:
  auth:
    container_name: auth_service
    hostname: auth_service
    build: .
    restart: always
    ports:
      - 8080:8080
    command: [
      "/app/service",
      "--config=prod.yaml"
    ]